"""empty message

Revision ID: a42cfc432b59
Revises: 
Create Date: 2023-11-02 22:36:28.968830

"""
from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a42cfc432b59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birth_place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('place', sa.String(length=70), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_birth_place_country'), 'birth_place', ['country'], unique=False)
    op.create_table('nba_season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_start', sa.Date(), nullable=True),
    sa.Column('season_end', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nba_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=6), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nba_team_city'), 'nba_team', ['city'], unique=False)
    op.create_index(op.f('ix_nba_team_name'), 'nba_team', ['name'], unique=False)
    op.create_table('nba_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('nationality', sa.String(length=20), nullable=True),
    sa.Column('injured', sa.Boolean(), nullable=True),
    # sa.Column('sport_league', sa.Enum('NBA', name='sportleague'), nullable=True),
    sa.Column('birth', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['birth'], ['birth_place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    sportleague_type = postgresql.ENUM('NBA', name='sportleague', create_type=False)
    sportleague_type.create(op.get_bind(), checkfirst=True)
    op.add_column('nba_player', sa.Column('sport_league', sportleague_type, nullable=True))
    op.create_index(op.f('ix_nba_player_name'), 'nba_player', ['name'], unique=False)
    op.create_index(op.f('ix_nba_player_nationality'), 'nba_player', ['nationality'], unique=False)
    op.create_table('nba_team_season',
    sa.Column('nba_team_id', sa.Integer(), nullable=True),
    sa.Column('nba_season_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nba_season_id'], ['nba_season.id'], ),
    sa.ForeignKeyConstraint(['nba_team_id'], ['nba_team.id'], )
    )
    op.create_table('nba_player_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('looses', sa.Integer(), nullable=True),
    sa.Column('minutes_played', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('field_goals_made', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('field_goals_attempted', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('field_goals_percentage', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('three_point_field_goals_made', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('three_point_field_goals_attempted', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('three_point_field_goals_percentage', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('free_throws_made', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('free_throws_attempted', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('free_throws_percentage', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('offensive_rebounds', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('defensive_rebounds', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('rebounds', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('assists', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('turnovers', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('steals', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('blocks', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('personal_fouls', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fantasy_points', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('double_doubles', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('triple_doubles', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('plus_minus', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['player'], ['nba_player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nba_player_season',
    sa.Column('nba_player_statistics_id', sa.Integer(), nullable=True),
    sa.Column('nba_season_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['nba_player_statistics_id'], ['nba_player_statistics.id'], ),
    sa.ForeignKeyConstraint(['nba_season_id'], ['nba_season.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nba_player_season')
    op.drop_table('nba_player_statistics')
    op.drop_table('nba_team_season')
    op.drop_index(op.f('ix_nba_player_nationality'), table_name='nba_player')
    op.drop_index(op.f('ix_nba_player_name'), table_name='nba_player')
    op.drop_table('nba_player')
    op.drop_index(op.f('ix_nba_team_name'), table_name='nba_team')
    op.drop_index(op.f('ix_nba_team_city'), table_name='nba_team')
    op.drop_table('nba_team')
    op.drop_table('nba_season')
    op.drop_index(op.f('ix_birth_place_country'), table_name='birth_place')
    op.drop_table('birth_place')
    # ### end Alembic commands ###
